### ISSUE TITLE
Determine what tech stack to use

### ISSUE THREAD

**Issue by avenmia** [avenmia/AlohaBirdsGame#1]
Here is an issue for discussing what tech stack to use. Considerations:
* What tech stacks are available for making an AR app?
  * Ideally, this will be cross platform and ios and android
* What are people currently familiar with? 
  * We mostly have web development people. I'm familiar with C# so would be open to using unity or a C# game engine but might be a steeper learning curve for people. There are C++ engines but I haven't used C++ since college and would be really difficult for newer people
* How do we handle the virtual birds in the tech stack?
  * What are the tools for generating virtual birds for the tech stack?
  * Does it make a performance difference if we use 3D models versus 2D sprites?
  * How does the tech stack handle animating the birds?
  * How easy is it to set up a mechanism for capturing the birds with the tech stack?

**Comment by wdpk** [comment]
Pokemon Go uses Unity, and Ninantic has an development kit based specifically for it to do a lot of the lifting on the AR side
https://www.xrtoday.com/augmented-reality/niantics-pokemon-go-engine-free-to-developers/
https://lightship.dev/products/ardk?hl=en

**Comment by avenmia** [comment]
We're going with unity
