### ISSUE TITLE
Add scene navigation between the Map and ARScene

### ISSUE THREAD

**Issue by avenmia** [avenmia/AlohaBirdsGame#10]
* From the MapScene, add a button that opens up the ARScene. 
* From the ARScene add a button that closes the ARScene and goes back to the MapScene

Follow what's outlined in the figma document for style and user flow. 

There may be a way to actually do this navigation from the phone's orientation such as if the phone is pointing down, it's on the map and when it's pointing up it's doing the AR Scene, but that's a nice to have.

**Comment by Lawrence-Kwok** [comment]
Resolved as of Pull Request #41
